title: learnelm.dev
description: A curated, opinionated path to learning Elm — from your first line of code to production. Free resources, sequenced and explained.
url: "https://learnelm.dev"
favicon: favicon.ico

author:
  name: Christian Ekrem
  email: christian.ekrem@gmail.com

remote_theme: cekrem/no-style-please
