services:
  jekyll:
    build: .
    command: >
      bundle exec jekyll serve --watch --force_polling --livereload --incremental --host 0.0.0.0
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - bundle-cache:/usr/local/bundle

volumes:
  bundle-cache:
